name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Instal Npm
        run: npm install

      - name: DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: elmaruis/mjss:latest

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/elru/mjs/mjss
            git pull origin main
            docker compose -f docker-compose.yml down
            docker pull elmaruis/mjss
            docker compose -f docker-compose.yml up -dname: Node.js

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Instal Npm
        run: npm install

      - name: DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: elmaruis/mjss:latest

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/elru/mjs/mjss
            git pull origin main
            docker compose -f docker-compose.yml down
            docker pull elmaruis/mjss
            docker compose -f docker-compose.yml up -d
